# Generated by Django 5.1.4 on 2025-01-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_order_shipped_alter_order_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_shipped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
