# Generated by Django 5.1.4 on 2025-01-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_order_date_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_country',
            field=models.CharField(max_length=256),
        ),
    ]
